src/Entity/Utilisateurs.php
<?php

namespace App\Entity;

use App\Repository\UtilisateursRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UtilisateursRepository::class)]
class Utilisateurs
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $Nom = null;

    #[ORM\Column(length: 50)]
    private ?string $Prenom = null;

    #[ORM\Column]
    private ?int $Age = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->Age;
    }

    public function setAge(int $Age): self
    {
        $this->Age = $Age;

        return $this;
    }
}

src/Form/Utilisateurs1Type.php
<?php

namespace App\Form;

use App\Entity\Utilisateurs;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class Utilisateurs1Type extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Nom')
            ->add('Prenom')
            ->add('Age')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Utilisateurs::class,
        ]);
    }
}

src/Form/UtilisateursType.php
<?php

namespace App\Form;

use App\Entity\Utilisateurs;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UtilisateursType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Nom')
            ->add('Prenom')
            ->add('Age')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Utilisateurs::class,
        ]);
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    #[Route('/home', name: 'app_home')]
    public function index(): Response
    {
        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController',
        ]);
    }
}

src/Controller/Utilisateurs2Controller.php
<?php

namespace App\Controller;

use App\Entity\Utilisateurs;
use App\Form\Utilisateurs1Type;
use App\Repository\UtilisateursRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/utilisateurs2')]
class Utilisateurs2Controller extends AbstractController
{
    #[Route('/', name: 'app_utilisateurs2_index', methods: ['GET'])]
    public function index(UtilisateursRepository $utilisateursRepository): Response
    {
        return $this->render('utilisateurs2/index.html.twig', [
            'utilisateurs' => $utilisateursRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_utilisateurs2_new', methods: ['GET', 'POST'])]
    public function new(Request $request, UtilisateursRepository $utilisateursRepository): Response
    {
        $utilisateur = new Utilisateurs();
        $form = $this->createForm(Utilisateurs1Type::class, $utilisateur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $utilisateursRepository->save($utilisateur, true);

            return $this->redirectToRoute('app_utilisateurs2_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('utilisateurs2/new.html.twig', [
            'utilisateur' => $utilisateur,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_utilisateurs2_show', methods: ['GET'])]
    public function show(Utilisateurs $utilisateur): Response
    {
        return $this->render('utilisateurs2/show.html.twig', [
            'utilisateur' => $utilisateur,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_utilisateurs2_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Utilisateurs $utilisateur, UtilisateursRepository $utilisateursRepository): Response
    {
        $form = $this->createForm(Utilisateurs1Type::class, $utilisateur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $utilisateursRepository->save($utilisateur, true);

            return $this->redirectToRoute('app_utilisateurs2_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('utilisateurs2/edit.html.twig', [
            'utilisateur' => $utilisateur,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_utilisateurs2_delete', methods: ['POST'])]
    public function delete(Request $request, Utilisateurs $utilisateur, UtilisateursRepository $utilisateursRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$utilisateur->getId(), $request->request->get('_token'))) {
            $utilisateursRepository->remove($utilisateur, true);
        }

        return $this->redirectToRoute('app_utilisateurs2_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/UtilisateursController.php
<?php

namespace App\Controller;

use App\Entity\Utilisateurs;
use App\Repository\UtilisateursRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;
use App\Form\UtilisateursType;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityManagerInterface;

class UtilisateursController extends AbstractController
{
    #[Route('/utilisateurs', name: 'app_utilisateurs')]
    public function index(UtilisateursRepository $utilisateurs)
    {

        $utiliRepo = $utilisateurs->findAll();

        return $this->render('utilisateurs/index.html.twig', [
            'Utilisateurs' =>  $utiliRepo,
        ]);
    }


    #[Route('/utilisateur/{id}', name: 'utilisateur_edit')]
    public function edit(int $id ,UtilisateursRepository $utilisateur)
    {

        $utiliRepo = $utilisateur->find($id);

        return $this->render('utilisateurs/edit.html.twig', [
            'utilisateur' =>  $utiliRepo,
        ]);
    }
    
    #[Route('/forme', name: 'forme')]
    public function forme(Request $request, EntityManagerInterface $em): Response
    {
        $utilisateurs=new Utilisateurs();
        $form=$this->createForm(UtilisateursType::class, $utilisateurs);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {

            $em->persist($utilisateurs);
            $em->flush();
            dump($utilisateurs);
            die;
        }

        return $this->render('utilisateurs/formulaire.html.twig', [
            'form' => $form->createView()
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>{% block title %}Welcome!{% endblock %}</title>
    <link
      rel="icon"
      href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>"
    />
    {# Run `composer require symfony/webpack-encore-bundle` to start using
    Symfony UX #} {% block stylesheets %}
    {{
      encore_entry_link_tags("app")
    }}
    {% endblock %} {% block javascripts %}
    {{
      encore_entry_script_tags("app")
    }}
    {% endblock %}
  </head>
  <body>
    {% block body %}{% endblock %}
  </body>
</html>

templates/home/index.html.twig
{% extends 'base.html.twig' %} {% block title %}Hello HomeController!{% endblock
%} {% block body %}
<style>
  .example-wrapper {
    margin: 1em auto;
    max-width: 800px;
    width: 95%;
    font: 18px/1.5 sans-serif;
  }
  .example-wrapper code {
    background: #f5f5f5;
    padding: 2px 6px;
  }
</style>

<div class="example-wrapper">
  <h1>Hello {{ controller_name }}! ✅</h1>
  <p>TESTESTSTSTSTSTSTT</p>
  <p>WEWEWEWEWEWEWEE</p>
  <p>MAMAMAMAMAMMAAMAMM</p>
  <p>dernier des derniers tests special pour Hicham</p>
</div>
{% endblock %}

templates/utilisateurs/edit.html.twig
{% block title %}Edit d'un utlisateur {% endblock %}



{% block body %}

<table border="1">

<tr>
    <td>{{ utilisateur.nom }}</td>
    <td>{{ utilisateur.prenom }}</td>
    <td>{{ utilisateur.age }}</td>

</tr>

</table>
{% endblock %}

templates/utilisateurs/formulaire.html.twig
{% block body %}
{{ form_start(form) }}
    {{ form_label(form.Nom) }}
    {{ form_widget(form.Nom) }}
    {{ form_label(form.Prenom) }}
    {{ form_widget(form.Prenom) }}
    {{ form_label(form.Age) }}
    {{ form_widget(form.Age) }}
    {{ form_rest(form) }}
        <button type="submit">Enregistrer</button>
    {{ form_end(form) }}

{% endblock %}

templates/utilisateurs/index.html.twig
{% block title %}Affichage de la liste Utilisateurs {% endblock %}

{% block body %}

<table border="1">
{% for p in Utilisateurs %}

<tr>
    <td>{{ p.nom }}</td>
    <td>{{ p.prenom }}</td>
    <td>{{ p.age }}</td>
    <td> <a href="{{path('utilisateur_edit', {id:p.id})}}">EDIT</a></td>
</tr>
{% endfor %}
</table>
{% endblock %}

templates/utilisateurs2/_delete_form.html.twig
<form method="post" action="{{ path('app_utilisateurs2_delete', {'id': utilisateur.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ utilisateur.id) }}">
    <button class="btn">Delete</button>
</form>

templates/utilisateurs2/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/utilisateurs2/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Utilisateurs{% endblock %}

{% block body %}
    <h1>Edit Utilisateurs</h1>

    {{ include('utilisateurs2/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_utilisateurs2_index') }}">back to list</a>

    {{ include('utilisateurs2/_delete_form.html.twig') }}
{% endblock %}

templates/utilisateurs2/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Utilisateurs index{% endblock %}

{% block body %}
    <h1>Utilisateurs index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Age</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for utilisateur in utilisateurs %}
            <tr>
                <td>{{ utilisateur.id }}</td>
                <td>{{ utilisateur.Nom }}</td>
                <td>{{ utilisateur.Prenom }}</td>
                <td>{{ utilisateur.Age }}</td>
                <td>
                    <a href="{{ path('app_utilisateurs2_show', {'id': utilisateur.id}) }}">show</a>
                    <a href="{{ path('app_utilisateurs2_edit', {'id': utilisateur.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_utilisateurs2_new') }}">Create new</a>
{% endblock %}

templates/utilisateurs2/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Utilisateurs{% endblock %}

{% block body %}
    <h1>Create new Utilisateurs</h1>

    {{ include('utilisateurs2/_form.html.twig') }}

    <a href="{{ path('app_utilisateurs2_index') }}">back to list</a>
{% endblock %}

templates/utilisateurs2/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Utilisateurs{% endblock %}

{% block body %}
    <h1>Utilisateurs</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ utilisateur.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ utilisateur.Nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ utilisateur.Prenom }}</td>
            </tr>
            <tr>
                <th>Age</th>
                <td>{{ utilisateur.Age }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_utilisateurs2_index') }}">back to list</a>

    <a href="{{ path('app_utilisateurs2_edit', {'id': utilisateur.id}) }}">edit</a>

    {{ include('utilisateurs2/_delete_form.html.twig') }}
{% endblock %}